export const data = [
  {
    id: 20000005,
    name: "研发族群",
    pid: -1,
    type: 1,
    children: [
      {
        id: 20000006,
        name: "设计",
        pid: 20000005,
        type: 2,
        children: [
          {
            id: 20000007,
            name: "产品设计",
            pid: 20000006,
            type: 3,
            children: [],
          },
          {
            id: 20000014,
            name: "产品设计2",
            pid: 20000006,
            type: 3,
            children: [
              {
                id: 30000006,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000007,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000008,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000009,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000010,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000011,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000012,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000013,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000014,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000015,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000016,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000017,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
              {
                id: 30000018,
                name: "string",
                pid: null,
                type: 4,
                children: [],
              },
            ],
          },
        ],
      },
      { id: 20000013, name: "设计2", pid: 20000005, type: 2, children: [] },
    ],
  },
  {
    id: 20000008,
    name: "测族群1",
    pid: -1,
    type: 1,
    children: [
      {
        id: 20000009,
        name: "测试序列1",
        pid: 20000008,
        type: 2,
        children: [
          {
            id: 20000010,
            name: "测试自学列",
            pid: 20000009,
            type: 3,
            children: [],
          },
        ],
      },
    ],
  },
  { id: 20000011, name: "测族群2", pid: -1, type: 1, children: [] },
  { id: 20000012, name: "测族群3", pid: -1, type: 1, children: [] },
];

const bb = {
  id: 20000013,
  title: "制造3组",
  nodeType: 1,
  pid: 10000001,
  pidNodeType: 0,
  type: null,
  adminId: null,
  adminName: null,
  children: [
    {
      id: 10000040,
      title: "制造3组-2",
      nodeType: 0,
      pid: 20000013,
      pidNodeType: 1,
      type: 20,
      adminId: "A0058810",
      adminName: "张丽",
      children: [],
      typeDesc: "子领域",
    },
    {
      id: 10000044,
      title: "制造3组-3",
      nodeType: 0,
      pid: 20000013,
      pidNodeType: 1,
      type: 20,
      adminId: "A0058810",
      adminName: "张丽",
      children: [],
      typeDesc: "子领域",
    },
    {
      id: 20000014,
      title: "制造3组-1",
      nodeType: 1,
      pid: 20000013,
      pidNodeType: 1,
      type: null,
      adminId: null,
      adminName: null,
      children: [],
      typeDesc: null,
      isLeaf: true,
    },
  ],
  typeDesc: null,
};
